const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.advert.Acts.HideBanner,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Cnds.OnInterstitialComplete,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{play: 0},
	{home: 0},
	{sounds: 0},
	{rate_us: 0},
	{share: 0},
	{logoGame: 0},
	{best_text: 0},
	{best_score: 0},
	{Touch: 0},
	{MoveTo: 0},
	{ScrollTo: 0},
	{camera: 0},
	{cameraPos2: 0},
	{block: 0},
	{Rotate: 0},
	{enemy: 0},
	{player: 0},
	{coin: 0},
	{Fade: 0},
	{Text: 0},
	{score: 0},
	{point1: 0},
	{point2: 0},
	{block2: 0},
	{Particles: 0},
	{sled: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{new_best_text: 0},
	{Logo: 0},
	{authorName: 0},
	{TiledBackground: 0},
	{Browser: 0},
	{MobileAdvert: 0},
	{GamePush: 0},
	{start: 0},
	{move: 0},
	{death: 0},
	{volume: 0},
	{layers_scale: 0},
	{addMob: 0}
];

self.InstanceType = {
	play: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	sounds: class extends self.ISpriteInstance {},
	rate_us: class extends self.ISpriteInstance {},
	share: class extends self.ISpriteInstance {},
	logoGame: class extends self.ISpriteInstance {},
	best_text: class extends self.ITextInstance {},
	best_score: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	cameraPos2: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	score: class extends self.ITextInstance {},
	point1: class extends self.ISpriteInstance {},
	point2: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	sled: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	new_best_text: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	authorName: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Browser: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {}
}